### ISSUE TITLE
User can select / deselect cards

### ISSUE THREAD

**Issue by StijnKing** [atos-reshape/atos#35]
### Problem

As a user I want to select or deselect a specific card.

#### User story

| **Nr** | **Who**               | **What** | **Why** | **Prio (MoSCoW)** |
| ------ | --------------------- | -------- | ------- | ----------------- |
| 1      | user   | want to be able to select/deselect a card  |     feel like it aligns with our business    |                   |

#### Acceptance criteria

- [ ] I can select a card
- [ ] I can deselect a card

### Tasks

- [ ] Endpoint for selecting a card
- [ ] Endpoint for deselecting a card
- [ ] Button for selecting a card / deselecting a card
