### ISSUE TITLE
Admin should be able to set the number of cards that can be picked in this round

### ISSUE THREAD

**Issue by VladimirCVB** [atos-reshape/atos#56]
### Problem

As an admin I want to set the maximum number of cards that can be picked during this round.

#### User story

| **Nr** | **Who**               | **What** | **Why** | **Prio (MoSCoW)** |
| ------ | --------------------- | -------- | ------- | ----------------- |
| 1      | Admin |  Set the maximum number of  cards that can be picked during the round|         |                   |

#### Example

A field in which as an admin I can enter the maximum number of cards that can be picked during the round.

#### Acceptance criteria

- [ ] I can enter the maximum number of cards to be picked

### Tasks

- [ ] Endpoint for entering the maximum number of cards
- [ ] Field to input the number
